### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by mipselqq** [u32i64/rvk#23]
What type generator did you use for this package?

**Comment by awaitlink** [comment]
I actually ended up creating both the types and the method lists manually according to the documentation (and then accepting PRs that fix some types according to real-world responses/usage which may unfortunately differ from the documentation).

Perhaps a better way would have been using the [official JSON API schema](https://github.com/vkcom/vk-api-schema). I don't exactly remember why I didn't use it, but it may have been because it wasn't exactly accurate with regards to the documentation or usage either.

**Comment by mipselqq** [comment]
Okay, thank you!
